### ISSUE TITLE
Doesn't limit saving to one term

### ISSUE THREAD

**Issue by helgatheviking** [5ally/my-term-selector#1]
In my implementation of this, I'm finding that changing the input type to radio (by itself) doesn't seem to restrict the post to saving only 1 term. https://github.com/helgatheviking/Radio-Buttons-for-Taxonomies/issues/53 I'm guessing that's because the entire form is not posted like a traditional html form. I looked at the core radio component and there's a state that's set that we're not yet doing. I think that's also related to the odd clicking behavior I'm seeing here https://github.com/helgatheviking/Radio-Buttons-for-Taxonomies/issues/51

Have you seen either of those in your version?

**Comment by 5ally** [comment]
Sorry @helgatheviking, I missed your message again. (Not watching this repo..)

But I'm not having any of those issues - clicking the radio buttons work fine and only one term is saved - please try this sample plugin: <strike>[wpse-332513.zip](https://github.com/5ally/my-term-selector/files/3087986/wpse-332513.zip)</strike> [wpse-332513.zip](https://github.com/5ally/my-term-selector/files/3088228/wpse-332513.zip).

Or check https://github.com/5ally/my-term-selector/tree/master/wpse-332513.

(You'll have to temporarily disable your plugin.)

**Comment by 5ally** [comment]
Perhaps you can compare your (copy of the original) `HierarchicalTermSelector` component with mine? :)

https://github.com/5ally/my-term-selector/blob/master/src/my-term-selector.js

**Comment by helgatheviking** [comment]
@5ally no worries! I appreciate any insight you have on this whenever you manage to send it. I think a file diff would be a great idea and will try to get to that soonish.

**Comment by helgatheviking** [comment]
A diff reveals quite a few more changes than I originally was aware of: https://www.diffchecker.com/e3ZVXG1K

Applying the rest of your changes does appear to correctly limit the saving to a single term. Yes!

**Comment by 5ally** [comment]
Hey @helgatheviking, I'm so glad to hear that! All the best. :)
